### ISSUE TITLE
关于app支付

### ISSUE THREAD

**Issue by Gavinzll** [ihaolin/alipay#1]
大神 菜鸟虚心请教
1.secret 字段具体指什么 我之前没有用到
2.app支付 中必填参数 ‘body’ 在组织请求数据时我没找到赋值位置   是否是2.0标准的？

**Comment by ihaolin** [comment]
1. **secret** 用于**业务数据签名**；
2. I'm sorry，APP支付由于环境问题，未能完整测试，**body**参数确实漏写，最近12月份支付宝官方APP支付确实有些更改，新的字段也已加上，**1.0.4**版本中已修复。

**Comment by Gavinzll** [comment]
大神
1.**secret**在app支付中未曾用到 ，而且我在我拿到的企业资料中也没有此项。如果存在单申请app支付，企业无此参的情况。是否要添加**Alipay**单参数构造，**newBuilder**方法也提供单参重载？
