### ISSUE TITLE
支付宝防钓鱼设置

### ISSUE THREAD

**Issue by wulinjie122** [ihaolin/alipay#13]
你好，请问有防钓鱼设置吗？今天网站碰到一个客户跳转到支付页面有钓鱼网站提示，结果直接被客户拉黑了。

官方文档：
②根据商户自身的业务需求或根据支付宝接口对应的特殊业务规则，有些参数也是需要传递过来的
如：即时到账中如果开通了防钓鱼策略，那么anti_phishing_key、exter_invoke_ip必须传递。

**Comment by ihaolin** [comment]
exter_invoke_ip参数是可以设置的，anti_phishing_key这个参数暂时没有，下个版本会加上。
