### ISSUE TITLE
支付宝WAP支付是否支持拉起APP

### ISSUE THREAD

**Issue by huaijinwoyu** [ihaolin/alipay#14]
RT，wap支付的app_pay 参数是否可以自定义设置？然后拉起来APP进行支付。

**Comment by ihaolin** [comment]
现在应该不支持，为什么不直接用APP Native支付？

**Comment by huaijinwoyu** [comment]
我想支付宝的付款二维码跟微信的合并起来，中转下请求用WAP来拉起来APP进行支付。

**Comment by ihaolin** [comment]
哦这场景倒遇到过，如果真能这样，我觉得微信不会干吧，应该会有屏蔽嫌疑。

**Comment by huaijinwoyu** [comment]
还有其他的解决方案吗?一般是怎么解决的呢？

**Comment by ihaolin** [comment]
微信里就用微信支付，也可以微信二维码生成，用户扫码就行了。[wepay](https://github.com/ihaolin/wepay)这个项目里有一部分实现。

**Comment by huaijinwoyu** [comment]
二码合一这种有解决方案吗？

**Comment by ihaolin** [comment]
这个没有研究过，二合一往往没有一来得好。
