### ISSUE TITLE
能否开放“支付超时时间”的设置

### ISSUE THREAD

**Issue by jacobwwang** [ihaolin/alipay#17]
您好！
我的一个项目有个需求，需要将支付超时时间设置为 15 分钟。查看您项目源码之后，不解是出于何种考虑，设置属性 me.hao0.alipay.core.Alipay.expired=1h。
目前解决方案是使用反射修改支付超时时间。
您是否能在下一版本，开放该属性的权限，可以自定义超时时间。
谢谢！

**Comment by ihaolin** [comment]
@JimmyLincole 不好意思，这个可能当时项目中使用的这个超时时间，没有提供超时配置，1.3.0版本中会加上。
