### ISSUE TITLE
菜鸟来了

### ISSUE THREAD

**Issue by Gavinzll** [ihaolin/alipay#2]
大神
1.**secre**t在app支付中未曾用到 ，而且我在我拿到的企业资料中也没有此项。如果存在单申请app支付，企业无此参的情况。是否要添加**Alipay**单参数构造，**newBuilder**方法也提供单参重载？
2.**body goodsType** 是否能够进入构参，防止第一次使用的同志们遗漏。

**Comment by ihaolin** [comment]
1. **secret** 在其他支付方式中会使用，这是一个**全局配置**，app支付构造支付参数时，如果只需要**app支付**，其实也可以随机传入一个串，不过会提供一个仅app支付的构造方式。
2. **必须参数**在代码中都会作异常检查，**body**已放入构参中，**goodsType**不是必须的不将放入构参。
3. 问题在**1.0.5**中已解决，发布可能有些延迟。
