### ISSUE TITLE
大神

### ISSUE THREAD

**Issue by Gavinzll** [ihaolin/alipay#3]
app 支付 AppPayDetail中goods type 是可空的，但是在参数检查中，还是要求参数不为空。

**Comment by ihaolin** [comment]
你用的最新版1.0.7吗，我看代码并没有检查goods_type呢

**Comment by Gavinzll** [comment]
me.hao0.alipay.core.Pays **line 144**

**Comment by ihaolin** [comment]
感谢，1.0.8中更正了。
