### ISSUE TITLE
m.h.alipay.demo.controller.Notifies - wap frontend sign: false

### ISSUE THREAD

**Issue by ryomasaber** [ihaolin/alipay#7]
你好，使用wap接口支付成功后的通知 签名验证不正确 这个有什么影响嘛？

**Comment by ihaolin** [comment]
有影响，签名验证是为了防止数据在传输过程中被篡改，这在与外部系统交互中很必要的一步，如果要求再高一些，就需要加密数据了。

**Comment by ryomasaber** [comment]
demo 里的验证函数有错误咯？

**Comment by ihaolin** [comment]
之前本地测试已通过，你看看是不是你的配置有什么问题。

**Comment by ryomasaber** [comment]
配置应该没问题吧 不然也不能发起支付请求且支付成功了
